name: Publish

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      PROJECT_NAME: Simple Frequency
      MODRINTH_ID: JUDvxSi8

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Variables
        run: |
          echo "VERSION=${GITHUB_REF_NAME}" >> "$GITHUB_ENV"

          echo "VERSION_NO_V=${VERSION#v}" >> "$GITHUB_ENV"

          DATAPACK_FOLDER="${PROJECT_NAME}"
          echo "DATAPACK_FOLDER=$DATAPACK_FOLDER" >> "$GITHUB_ENV"

          DATAPACK_FILE="${PROJECT_NAME} ${GITHUB_REF_NAME}.zip"
          echo "DATAPACK_FILE=$DATAPACK_FILE" >> "$GITHUB_ENV"

          DATAPACK_FILE_NO_SPACES="${DATAPACK_FILE// /-}"
          echo "DATAPACK_FILE_NO_SPACES=$DATAPACK_FILE_NO_SPACES" >> "$GITHUB_ENV"

      - name: Extract Changelog
        id: changelog
        run: |
          changelog=$(awk "/^## \[${VERSION//./\\.}\]/ {flag=1; next} /^## / {flag=0} flag" CHANGELOG.md)
          changelog="${changelog//'%'/'%25'}"
          echo "log<<EOF" >> "$GITHUB_OUTPUT"
          echo "${changelog}" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Zip Data Pack
        run: |
          cd "src/${DATAPACK_FOLDER}"
          zip -r "$OLDPWD/${DATAPACK_FILE}" ./*
          cp "$OLDPWD/${DATAPACK_FILE}" "$OLDPWD/${DATAPACK_FILE_NO_SPACES}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.DATAPACK_FILE_NO_SPACES }}
          body: ${{ steps.changelog.outputs.log }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Datapack
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ${{ env.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          name: ${{ env.PROJECT_NAME }} ${{ env.VERSION }}
          version: ${{ env.VERSION_NO_V }}
          version-type: release
          loaders: |
            datapack
          dependencies: |
            simple-radio
          game-versions: |
            [1.20,1.20.6]
          changelog: ${{ steps.changelog.outputs.log }}
          files: ${{ env.DATAPACK_FILE }}
