name: Publish

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      PROJECT_NAME: Simple Frequency
      MODRINTH_ID: JUDvxSi8

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set variables
        run: |
          echo "VERSION=${GITHUB_REF_NAME#v}" >> "$GITHUB_ENV"
          ZIP_NAME="${PROJECT_NAME// /-}-${GITHUB_REF_NAME}.zip"
          echo "ZIP_NAME=$ZIP_NAME" >> "$GITHUB_ENV"

      - name: Extract changelog
        id: changelog
        run: |
          changelog=$(awk "/^## ${VERSION//./\\.}/ {flag=1; next} /^## / {flag=0} flag" changelog.md)
          changelog="${changelog//'%'/'%25'}"
          {
            echo 'log<<EOF'
            echo "$changelog"
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: Create ZIP archive
        run: |
          cd "src/${PROJECT_NAME}"
          zip -r "$OLDPWD/${ZIP_NAME}" ./*

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ZIP_NAME }}
          body: ${{ steps.changelog.outputs.log }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish datapack
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ${{ env.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          name: Version ${{ env.VERSION }}
          version: ${{ env.VERSION }}
          version-type: release
          loaders: |
            datapack
          dependencies: |
            simple-radio
          game-versions: |
            [1.20,1.20.6]
          changelog: ${{ steps.changelog.outputs.log }}
          files: ${{ env.ZIP_NAME }}
