name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: Simple Frequency
      MODRINTH_ID: JUDvxSi8

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set variables
        run: |
          echo "VERSION=${GITHUB_REF_NAME#v}" >> "$GITHUB_ENV"
          echo "ZIP_NAME=${PROJECT_NAME} ${GITHUB_REF_NAME}.zip" >> "$GITHUB_ENV"

      - name: Create ZIP archive
        run: |
          zip -r "$ZIP_NAME" "src/$PROJECT_NAME"

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ZIP_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish datapack
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ${{ env.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          version: ${{ env.VERSION }}
